kind = "DojoModel"
class_hash = "0x156d904cdeb8b3fd71a1380ab0ffb895793c41978b597d08be012890a4e483f"
original_class_hash = "0x156d904cdeb8b3fd71a1380ab0ffb895793c41978b597d08be012890a4e483f"
abi = "manifests/dev/base/abis/models/p_dash-StageId-76d39641.json"
tag = "p_dash-StageId"
manifest_name = "p_dash-StageId-76d39641"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "value"
type = "usize"
key = false
