kind = "DojoModel"
class_hash = "0x7b920dc810b70883da634a6463d9e3dd9bc21ebb3ebd2f720dba46a5b6121a2"
original_class_hash = "0x7b920dc810b70883da634a6463d9e3dd9bc21ebb3ebd2f720dba46a5b6121a2"
abi = "manifests/dev/base/abis/models/pixelaw-Stage-549fb0e1.json"
tag = "pixelaw-Stage"
manifest_name = "pixelaw-Stage-549fb0e1"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "w"
type = "u32"
key = false

[[members]]
name = "h"
type = "u32"
key = false
