kind = "DojoModel"
class_hash = "0x392e6a537f53883754b40ef3bfebb72683941cb92e22611368a7a2927e24a3c"
original_class_hash = "0x392e6a537f53883754b40ef3bfebb72683941cb92e22611368a7a2927e24a3c"
abi = "manifests/dev/base/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[members]]
name = "key"
type = "felt252"
key = true

[[members]]
name = "value"
type = "ContractAddress"
key = false
