kind = "DojoModel"
class_hash = "0x643c727dbdad863d58aea082bfa066e9b2fed60f4c1fb78c7b0dbdfeb6175b2"
original_class_hash = "0x643c727dbdad863d58aea082bfa066e9b2fed60f4c1fb78c7b0dbdfeb6175b2"
abi = "manifests/dev/base/abis/models/pixelaw-Stage-549fb0e1.json"
tag = "pixelaw-Stage"
qualified_path = "p_dash::models::stage::stage"
manifest_name = "pixelaw-Stage-549fb0e1"

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "w"
type = "u32"
key = false

[[members]]
name = "h"
type = "u32"
key = false

[[members]]
name = "creator"
type = "ContractAddress"
key = false
