kind = "DojoModel"
class_hash = "0x379b4f97b2fad046187bf6fa4243494c56af27be1a34e5030979fc82a03cf09"
original_class_hash = "0x379b4f97b2fad046187bf6fa4243494c56af27be1a34e5030979fc82a03cf09"
abi = "manifests/dev/base/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "app"
type = "ContractAddress"
key = false

[[members]]
name = "color"
type = "u32"
key = false

[[members]]
name = "created_at"
type = "u64"
key = false

[[members]]
name = "updated_at"
type = "u64"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "text"
type = "felt252"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
