kind = "DojoModel"
class_hash = "0x480f000803ac3f522c60f5781f3ebe4242eb3cde658027682092a689b3d5945"
original_class_hash = "0x480f000803ac3f522c60f5781f3ebe4242eb3cde658027682092a689b3d5945"
abi = "manifests/dev/base/abis/models/pixelaw-App-36504565.json"
tag = "pixelaw-App"
manifest_name = "pixelaw-App-36504565"

[[members]]
name = "system"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "manifest"
type = "felt252"
key = false

[[members]]
name = "icon"
type = "felt252"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
