[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x5cb56865911cf7329f62323a0721c2731f55db9e82c8f41cd0ce81bcdd7317"
transaction_hash = "0x7c81d487215a052b0eda600fc6761ba80b1ecb3f6fb572ead64b6d40792f894"
block_number = 3
seed = ""
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2644b3b291aa0a3e813bb750f960d3efac87c76aeec9bad2ddb7bce576413a1"
class_hash = "0x680cb51f2ba01608b7ea6b2c1f7d3f4927e1f34601266c44adf3e66ebb7586f"
original_class_hash = "0x680cb51f2ba01608b7ea6b2c1f7d3f4927e1f34601266c44adf3e66ebb7586f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-actions-16928a49.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-actions"
systems = [
    "init",
    "update_permission",
    "update_app",
    "schedule_queue",
    "process_queue",
    "update_pixel",
    "alert_player",
    "set_instruction",
]
manifest_name = "pixelaw-actions-16928a49"

[[contracts]]
kind = "DojoContract"
address = "0x630d49e77e471d8a2708efb53a23b615777d3dcfe44b89579659333a032add7"
class_hash = "0x70d4cf856e1e43a8b7b539e393eea08cfd5ca8dc7b35cc91602413d707bca28"
original_class_hash = "0x70d4cf856e1e43a8b7b539e393eea08cfd5ca8dc7b35cc91602413d707bca28"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pixelaw-p_dash_actions-374d4b2d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_dash_actions"
systems = [
    "init",
    "interact",
    "initialize_stage",
    "put_block",
]
manifest_name = "pixelaw-p_dash_actions-374d4b2d"

[[models]]
kind = "DojoModel"
class_hash = "0x34204d56b9f6a93b305e54a27b5e8e593f159f87212fcf39c770020b03bfce5"
original_class_hash = "0x34204d56b9f6a93b305e54a27b5e8e593f159f87212fcf39c770020b03bfce5"
abi = "manifests/dev/deployment/abis/models/pixelaw-App-36504565.json"
tag = "pixelaw-App"
manifest_name = "pixelaw-App-36504565"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "manifest"
type = "felt252"
key = false

[[models.members]]
name = "icon"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
original_class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppName-3b816829.json"
tag = "pixelaw-AppName"
manifest_name = "pixelaw-AppName-3b816829"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "system"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
original_class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppUser-4eda3c52.json"
tag = "pixelaw-AppUser"
manifest_name = "pixelaw-AppUser-4eda3c52"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x76f9cd1817f7802e3c9dbe1993251597832ce23f85a7142a891c1162748541e"
original_class_hash = "0x76f9cd1817f7802e3c9dbe1993251597832ce23f85a7142a891c1162748541e"
abi = "manifests/dev/deployment/abis/models/pixelaw-Block-656ed65c.json"
tag = "pixelaw-Block"
manifest_name = "pixelaw-Block-656ed65c"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "block"
type = "BlockType"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
original_class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
abi = "manifests/dev/deployment/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "value"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
original_class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
abi = "manifests/dev/deployment/abis/models/pixelaw-Instruction-4c7c4844.json"
tag = "pixelaw-Instruction"
manifest_name = "pixelaw-Instruction-4c7c4844"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "selector"
type = "felt252"
key = true

[[models.members]]
name = "instruction"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
original_class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
abi = "manifests/dev/deployment/abis/models/pixelaw-Permissions-72b77307.json"
tag = "pixelaw-Permissions"
manifest_name = "pixelaw-Permissions-72b77307"

[[models.members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "permission"
type = "Permission"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
original_class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
abi = "manifests/dev/deployment/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "app"
type = "ContractAddress"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "created_at"
type = "u64"
key = false

[[models.members]]
name = "updated_at"
type = "u64"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
original_class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
abi = "manifests/dev/deployment/abis/models/pixelaw-QueueItem-549a17f2.json"
tag = "pixelaw-QueueItem"
manifest_name = "pixelaw-QueueItem-549a17f2"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "valid"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
original_class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
abi = "manifests/dev/deployment/abis/models/pixelaw-Snake-62b876d4.json"
tag = "pixelaw-Snake"
manifest_name = "pixelaw-Snake-62b876d4"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "length"
type = "u8"
key = false

[[models.members]]
name = "first_segment_id"
type = "u32"
key = false

[[models.members]]
name = "last_segment_id"
type = "u32"
key = false

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "is_dying"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
original_class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
abi = "manifests/dev/deployment/abis/models/pixelaw-SnakeSegment-302de0d8.json"
tag = "pixelaw-SnakeSegment"
manifest_name = "pixelaw-SnakeSegment-302de0d8"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "previous_id"
type = "u32"
key = false

[[models.members]]
name = "next_id"
type = "u32"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_color"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[models.members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36c0f3579aa8b3c6364cc6ff2a20eff679e73c7eccc56d562252d26af9fcbae"
original_class_hash = "0x36c0f3579aa8b3c6364cc6ff2a20eff679e73c7eccc56d562252d26af9fcbae"
abi = "manifests/dev/deployment/abis/models/pixelaw-Stage-549fb0e1.json"
tag = "pixelaw-Stage"
manifest_name = "pixelaw-Stage-549fb0e1"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "w"
type = "u32"
key = false

[[models.members]]
name = "h"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x20fa6d6f08426bd6a804d9aa8346f21456e2974d5f6a5aec23ecbba5afa52a"
original_class_hash = "0x20fa6d6f08426bd6a804d9aa8346f21456e2974d5f6a5aec23ecbba5afa52a"
abi = "manifests/dev/deployment/abis/models/pixelaw-StageId-6b09362b.json"
tag = "pixelaw-StageId"
manifest_name = "pixelaw-StageId-6b09362b"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "usize"
key = false
