[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x29843b0e20802c0147b8c5cb51a7964aa4c0f0ccd14a1b329c73615ad510822"
seed = ""
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
class_hash = "0x206aec9aa6320cfc5ad332f1863f10a257f168038097c8b571bf63fb2750e56"
original_class_hash = "0x206aec9aa6320cfc5ad332f1863f10a257f168038097c8b571bf63fb2750e56"
base_class_hash = "0x0"
abi = "manifests/dev/deployment/abis/contracts/-actions-3c2ef21d.json"
reads = []
writes = []
init_calldata = []
tag = "-actions"
manifest_name = "-actions-3c2ef21d"

[[models]]
kind = "DojoModel"
class_hash = "0x5e8ceb6aae8d965b76e0e629e0a12c9cd08803ae5b7846d915c11a71b250802"
original_class_hash = "0x5e8ceb6aae8d965b76e0e629e0a12c9cd08803ae5b7846d915c11a71b250802"
abi = "manifests/dev/deployment/abis/models/p_dash-Block-63c3c136.json"
tag = "p_dash-Block"
manifest_name = "p_dash-Block-63c3c136"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "block"
type = "BlockType"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xe388ce3a843f84050025b74ecf8cb1330d0074c6d93c8e52b2152c3ecab873"
original_class_hash = "0xe388ce3a843f84050025b74ecf8cb1330d0074c6d93c8e52b2152c3ecab873"
abi = "manifests/dev/deployment/abis/models/p_dash-Stage-93715983.json"
tag = "p_dash-Stage"
manifest_name = "p_dash-Stage-93715983"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "w"
type = "u32"
key = false

[[models.members]]
name = "h"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x298c3ac0db82f0a3983bd2199c57b314d4b54085b281f93320cd44061678de5"
original_class_hash = "0x298c3ac0db82f0a3983bd2199c57b314d4b54085b281f93320cd44061678de5"
abi = "manifests/dev/deployment/abis/models/p_dash-StageId-76d39641.json"
tag = "p_dash-StageId"
manifest_name = "p_dash-StageId-76d39641"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "usize"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x480f000803ac3f522c60f5781f3ebe4242eb3cde658027682092a689b3d5945"
original_class_hash = "0x480f000803ac3f522c60f5781f3ebe4242eb3cde658027682092a689b3d5945"
abi = "manifests/dev/deployment/abis/models/pixelaw-App-36504565.json"
tag = "pixelaw-App"
manifest_name = "pixelaw-App-36504565"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "manifest"
type = "felt252"
key = false

[[models.members]]
name = "icon"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x59aa1a81d30a50b3296542736036e5c96a67e0d726a1014b184c029c953e5bd"
original_class_hash = "0x59aa1a81d30a50b3296542736036e5c96a67e0d726a1014b184c029c953e5bd"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppName-3b816829.json"
tag = "pixelaw-AppName"
manifest_name = "pixelaw-AppName-3b816829"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "system"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x8f2440e890643c2014f4829d82257d63ead4fa1ebf2bbe0753155e0dd83a92"
original_class_hash = "0x8f2440e890643c2014f4829d82257d63ead4fa1ebf2bbe0753155e0dd83a92"
abi = "manifests/dev/deployment/abis/models/pixelaw-AppUser-4eda3c52.json"
tag = "pixelaw-AppUser"
manifest_name = "pixelaw-AppUser-4eda3c52"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x392e6a537f53883754b40ef3bfebb72683941cb92e22611368a7a2927e24a3c"
original_class_hash = "0x392e6a537f53883754b40ef3bfebb72683941cb92e22611368a7a2927e24a3c"
abi = "manifests/dev/deployment/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "value"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x51ff36f3962b27c99de7e95fb9fc96fdef1186d45818085b5757d5906929a93"
original_class_hash = "0x51ff36f3962b27c99de7e95fb9fc96fdef1186d45818085b5757d5906929a93"
abi = "manifests/dev/deployment/abis/models/pixelaw-Instruction-4c7c4844.json"
tag = "pixelaw-Instruction"
manifest_name = "pixelaw-Instruction-4c7c4844"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "selector"
type = "felt252"
key = true

[[models.members]]
name = "instruction"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2b85c97f5ebbc06f3c2d6cfa4b5af8ae4f2deee17c3b5c3000cd16c6488227d"
original_class_hash = "0x2b85c97f5ebbc06f3c2d6cfa4b5af8ae4f2deee17c3b5c3000cd16c6488227d"
abi = "manifests/dev/deployment/abis/models/pixelaw-Permissions-72b77307.json"
tag = "pixelaw-Permissions"
manifest_name = "pixelaw-Permissions-72b77307"

[[models.members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "permission"
type = "Permission"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x379b4f97b2fad046187bf6fa4243494c56af27be1a34e5030979fc82a03cf09"
original_class_hash = "0x379b4f97b2fad046187bf6fa4243494c56af27be1a34e5030979fc82a03cf09"
abi = "manifests/dev/deployment/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "app"
type = "ContractAddress"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "created_at"
type = "u64"
key = false

[[models.members]]
name = "updated_at"
type = "u64"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6955a5481bde098ffbf3745a76030ae37aa5843ae37362581f0c1ad467535a0"
original_class_hash = "0x6955a5481bde098ffbf3745a76030ae37aa5843ae37362581f0c1ad467535a0"
abi = "manifests/dev/deployment/abis/models/pixelaw-QueueItem-549a17f2.json"
tag = "pixelaw-QueueItem"
manifest_name = "pixelaw-QueueItem-549a17f2"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "valid"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d10266ba502b0b33ea235f38fc211646d946ec25e37574df91c08e56baf4e6"
original_class_hash = "0x3d10266ba502b0b33ea235f38fc211646d946ec25e37574df91c08e56baf4e6"
abi = "manifests/dev/deployment/abis/models/pixelaw-Snake-62b876d4.json"
tag = "pixelaw-Snake"
manifest_name = "pixelaw-Snake-62b876d4"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "length"
type = "u8"
key = false

[[models.members]]
name = "first_segment_id"
type = "u32"
key = false

[[models.members]]
name = "last_segment_id"
type = "u32"
key = false

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "is_dying"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x10880cb541815617b59f0e6bbbfb5172e865fb2ab0b56130f899b26b0ce4f3f"
original_class_hash = "0x10880cb541815617b59f0e6bbbfb5172e865fb2ab0b56130f899b26b0ce4f3f"
abi = "manifests/dev/deployment/abis/models/pixelaw-SnakeSegment-302de0d8.json"
tag = "pixelaw-SnakeSegment"
manifest_name = "pixelaw-SnakeSegment-302de0d8"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "previous_id"
type = "u32"
key = false

[[models.members]]
name = "next_id"
type = "u32"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_color"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[models.members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false
