kind = "DojoContract"
class_hash = "0x3a7ad348c53d1a67988ec1006ae24637c39975e30d443f87aa4b94e86501fcc"
original_class_hash = "0x3a7ad348c53d1a67988ec1006ae24637c39975e30d443f87aa4b94e86501fcc"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/pixelaw-p_dash_actions-374d4b2d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_dash_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "init",
    "initialize_stage",
    "put_block",
]
manifest_name = "pixelaw-p_dash_actions-374d4b2d"
