[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/release/deployment/abis/dojo-world.json"
address = "0x263ae44e5414519a5c5a135cccaf3d9d7ee196d37e8de47a178da91f3de9b34"
seed = "pixelaw"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "release"
rpc_url = "https://api.cartridge.gg/x/pixelaw-dev/katana/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/release/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6c2ffdd97cb5a1bca13de416adb23a1d0e24ae3c805114b2100f6af95a7f60e"
class_hash = "0x8fc78d962baf4651c69c567cdd14f4e0d071fcd0a874fe72abd2394b221ffc"
original_class_hash = "0x8fc78d962baf4651c69c567cdd14f4e0d071fcd0a874fe72abd2394b221ffc"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/release/deployment/abis/contracts/pixelaw-actions-16928a49.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-actions"
systems = [
    "init",
    "update_permission",
    "schedule_queue",
    "process_queue",
    "update_pixel",
    "alert_player",
    "set_instruction",
]
manifest_name = "pixelaw-actions-16928a49"

[[contracts]]
kind = "DojoContract"
address = "0x1d7b4801ae82c121359b28cac257e0c5b436532f91d04ac8890c3a25bc6e44e"
class_hash = "0x2aec1707b289ec5f94bba0082f77ac1d54ee862d064f38d0fd29cf2007569ef"
original_class_hash = "0x2aec1707b289ec5f94bba0082f77ac1d54ee862d064f38d0fd29cf2007569ef"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/release/deployment/abis/contracts/pixelaw-p_dash_actions-374d4b2d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_dash_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "init",
    "put_block",
]
manifest_name = "pixelaw-p_dash_actions-374d4b2d"

[[models]]
kind = "DojoModel"
class_hash = "0x4107d94a66470b68d2e06102c87937c03cca51fafa84a3a4fc45c95a4d2403c"
original_class_hash = "0x4107d94a66470b68d2e06102c87937c03cca51fafa84a3a4fc45c95a4d2403c"
abi = "manifests/release/deployment/abis/models/pixelaw-App-36504565.json"
tag = "pixelaw-App"
qualified_path = "pixelaw::core::models::registry::app"
manifest_name = "pixelaw-App-36504565"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "icon"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
original_class_hash = "0x7d54c34e9b4215ceaada6950e0b521ef3892de01fbaea2c8323e8c2cf3329c8"
abi = "manifests/release/deployment/abis/models/pixelaw-AppName-3b816829.json"
tag = "pixelaw-AppName"
qualified_path = "pixelaw::core::models::registry::app_name"
manifest_name = "pixelaw-AppName-3b816829"

[[models.members]]
name = "name"
type = "felt252"
key = true

[[models.members]]
name = "system"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
original_class_hash = "0x3d55e23acf8df5ef0c25b76d5a6b7765c241c494af075c7ce3858568bec45f1"
abi = "manifests/release/deployment/abis/models/pixelaw-AppUser-4eda3c52.json"
tag = "pixelaw-AppUser"
qualified_path = "pixelaw::core::models::registry::app_user"
manifest_name = "pixelaw-AppUser-4eda3c52"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x23ef82c8a79694e0a86f1bf829c499ca883ccc047bbdc05dd983bd153cdc79f"
original_class_hash = "0x23ef82c8a79694e0a86f1bf829c499ca883ccc047bbdc05dd983bd153cdc79f"
abi = "manifests/release/deployment/abis/models/pixelaw-Block-656ed65c.json"
tag = "pixelaw-Block"
qualified_path = "p_dash::models::block::block"
manifest_name = "pixelaw-Block-656ed65c"

[[models.members]]
name = "stage_id"
type = "usize"
key = true

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "blocktype"
type = "BlockType"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
original_class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
abi = "manifests/release/deployment/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
qualified_path = "pixelaw::core::models::registry::core_actions_address"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[models.members]]
name = "key"
type = "felt252"
key = true

[[models.members]]
name = "value"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
original_class_hash = "0x710dc73b9f03542890421c368ca53fe61416010f69709337bc7b40b9c3115af"
abi = "manifests/release/deployment/abis/models/pixelaw-Instruction-4c7c4844.json"
tag = "pixelaw-Instruction"
qualified_path = "pixelaw::core::models::registry::instruction"
manifest_name = "pixelaw-Instruction-4c7c4844"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "selector"
type = "felt252"
key = true

[[models.members]]
name = "instruction"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
original_class_hash = "0x7083f333ceabd1e174c4f5b129b7d5cfeaccd7b4fcc5ea2e5a264cce7dc302"
abi = "manifests/release/deployment/abis/models/pixelaw-Permissions-72b77307.json"
tag = "pixelaw-Permissions"
qualified_path = "pixelaw::core::models::permissions::permissions"
manifest_name = "pixelaw-Permissions-72b77307"

[[models.members]]
name = "allowing_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "allowed_app"
type = "ContractAddress"
key = true

[[models.members]]
name = "permission"
type = "Permission"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
original_class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
abi = "manifests/release/deployment/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
qualified_path = "pixelaw::core::models::pixel::pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "app"
type = "ContractAddress"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "created_at"
type = "u64"
key = false

[[models.members]]
name = "updated_at"
type = "u64"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "action"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
original_class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
abi = "manifests/release/deployment/abis/models/pixelaw-QueueItem-549a17f2.json"
tag = "pixelaw-QueueItem"
qualified_path = "pixelaw::core::models::queue::queue_item"
manifest_name = "pixelaw-QueueItem-549a17f2"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "valid"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
original_class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
abi = "manifests/release/deployment/abis/models/pixelaw-Snake-62b876d4.json"
tag = "pixelaw-Snake"
qualified_path = "pixelaw::apps::snake::app::snake"
manifest_name = "pixelaw-Snake-62b876d4"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "length"
type = "u8"
key = false

[[models.members]]
name = "first_segment_id"
type = "u32"
key = false

[[models.members]]
name = "last_segment_id"
type = "u32"
key = false

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models.members]]
name = "color"
type = "u32"
key = false

[[models.members]]
name = "text"
type = "felt252"
key = false

[[models.members]]
name = "is_dying"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
original_class_hash = "0x19a1ae61a4fb0ac303e15a4ca4befa5ae3962625eb37f379b941815e321191f"
abi = "manifests/release/deployment/abis/models/pixelaw-SnakeSegment-302de0d8.json"
tag = "pixelaw-SnakeSegment"
qualified_path = "pixelaw::apps::snake::app::snake_segment"
manifest_name = "pixelaw-SnakeSegment-302de0d8"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "previous_id"
type = "u32"
key = false

[[models.members]]
name = "next_id"
type = "u32"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_color"
type = "u32"
key = false

[[models.members]]
name = "pixel_original_text"
type = "felt252"
key = false

[[models.members]]
name = "pixel_original_app"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36c0f3579aa8b3c6364cc6ff2a20eff679e73c7eccc56d562252d26af9fcbae"
original_class_hash = "0x36c0f3579aa8b3c6364cc6ff2a20eff679e73c7eccc56d562252d26af9fcbae"
abi = "manifests/release/deployment/abis/models/pixelaw-Stage-549fb0e1.json"
tag = "pixelaw-Stage"
qualified_path = "p_dash::models::stage::stage"
manifest_name = "pixelaw-Stage-549fb0e1"

[[models.members]]
name = "id"
type = "usize"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "w"
type = "u32"
key = false

[[models.members]]
name = "h"
type = "u32"
key = false
