kind = "DojoContract"
class_hash = "0x684ff06480ae70f340a81e666e820525121465b3229122649c574832a1fed57"
original_class_hash = "0x684ff06480ae70f340a81e666e820525121465b3229122649c574832a1fed57"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/p_dash-actions-19d56844.json"
reads = []
writes = []
init_calldata = []
tag = "p_dash-actions"
systems = [
    "init",
    "interact",
    "initialize_stage",
    "put_block",
]
manifest_name = "p_dash-actions-19d56844"
