kind = "DojoContract"
class_hash = "0x25ef6619aecd89cc45ad10c70f2588ccebd6254ed418353b815f26733005b7a"
original_class_hash = "0x25ef6619aecd89cc45ad10c70f2588ccebd6254ed418353b815f26733005b7a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-p_dash_actions-374d4b2d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_dash_actions"
systems = [
    "init",
    "interact",
    "initialize_stage",
    "put_block",
]
manifest_name = "pixelaw-p_dash_actions-374d4b2d"
