kind = "DojoContract"
class_hash = "0x21af2cce9f3f68d21f45d5536e50a293af1f59fc106830cf4d1f608ffcf6345"
original_class_hash = "0x21af2cce9f3f68d21f45d5536e50a293af1f59fc106830cf4d1f608ffcf6345"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pixelaw-p_dash_actions-374d4b2d.json"
reads = []
writes = []
init_calldata = []
tag = "pixelaw-p_dash_actions"
systems = [
    "on_pre_update",
    "on_post_update",
    "init",
    "put_block",
]
manifest_name = "pixelaw-p_dash_actions-374d4b2d"
