[world]
description = "pixelaw world"
name = "pixelaw"
seed = "pixelaw"

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
keystore_path = "sepolia.deployer.keystore.json"
account_address = "0x02107b2bcC750F51E70cFb9c53583a54eAf86DaC60C6EFBDECf18F7eE398Cb89"
world_address = "0x2bf4d3aa0dced89d37d8c3b4ff6a05895c0af32ff3baf9b02abf8504e53eaad"


[writers]
"pixelaw-App" = ["pixelaw-actions"]
"pixelaw-AppName" = ["pixelaw-actions"]
"pixelaw-AppUser" = ["pixelaw-actions"]
"pixelaw-CoreActionsAddress" = ["pixelaw-actions"]
"pixelaw-QueueScheduled" = ["pixelaw-actions"]
"pixelaw-QueueProcessed" = ["pixelaw-actions"]
"pixelaw-Alert" = ["pixelaw-actions"]
"pixelaw-Pixel" = [
    "pixelaw-actions",
    "pixelaw-paint_actions",
    "pixelaw-snake_actions",
]
"pixelaw-QueueItem" = ["pixelaw-actions"]
"pixelaw-Snake" = ["pixelaw-actions", "pixelaw-snake_actions"]
"pixelaw-RTree" = ["pixelaw-actions"]
"pixelaw-Area" = ["pixelaw-actions"]
"pixelaw-SnakeSegment" = ["pixelaw-snake_actions"]

# p_dash
"pixelaw-Block" = ["pixelaw-p_dash_actions"]
"pixelaw-Stage" = ["pixelaw-p_dash_actions"]
