[package]
cairo-version = "=2.8.4"
name = "p_dash"
version = "0.0.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.5.20" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.6" }
pixelaw_test_helpers = { git = "https://github.com/pixelaw/core", tag = "v0.5.20" }


[[target.starknet-contract]]
sierra = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "pixelaw::core::actions::actions",
    "pixelaw::apps::paint::app::paint_actions",
    "pixelaw::apps::snake::app::snake_actions",
]

[tool.fmt]
sort-module-level-items = true

[scripts]
init = "./scripts/init.sh"
init_auth = "./scripts/init_auth.sh"
stage_test = "./scripts/stage_test.sh"
