[package]
cairo-version = "=2.7.0"
name = "p_dash"
version = "0.0.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
# pixelaw = { git = "https://github.com/pixelaw/core", tag = "v0.3.47" }
pixelaw = { git = "https://github.com/pixelaw/core", rev = "9a1484092e1b06702e5509eeacfdaea0a92ce72e" }
dojo = { git = "https://github.com/dojoengine/dojo", rev = "v1.0.0-alpha.11" }

[[target.dojo]]
build-external-contracts = [
    "pixelaw::apps::snake::app::snake",
    "pixelaw::apps::snake::app::snake_segment",
    "pixelaw::core::models::pixel::pixel",
    "pixelaw::core::models::pixel::Pixel",
    "pixelaw::core::models::pixel::PixelUpdate",
    "pixelaw::core::models::queue::queue_item",
    "pixelaw::core::models::registry::app",
    "pixelaw::core::models::registry::app_name",
    "pixelaw::core::models::registry::app_user",
    "pixelaw::core::models::registry::instruction",
    "pixelaw::core::models::registry::core_actions_address",
    "pixelaw::core::models::permissions::permissions",
    "pixelaw::core::utils::get_core_actions",
    "pixelaw::core::utils::Direction",
    "pixelaw::core::utils::Position",
    "pixelaw::core::utils::DefaultParameters",
    "pixelaw::core::actions::actions",
    "pixelaw::core::actions::IActionsDispatcher",
    "pixelaw::core::actions::IActionsDispatcherTrait",
]

[scripts]
init_auth = "./scripts/init_auth.sh"
stage_test = "./scripts/stage_test.sh"
