[package]
cairo-version = "=2.7.0"
name = "p_dash"
version = "0.0.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
# pixelaw = { path = "/Users/asumayamada/Private/pixelaw/core/contracts" }
pixelaw = { git = "https://github.com/pixelaw/core", rev = "c60d9248d0ebe350600a3a2c4df81796e1a4d2b3" }

[[target.dojo]]
build-external-contracts = [
    "pixelaw::apps::snake::app::snake",
    "pixelaw::apps::snake::app::snake_segment",
    "pixelaw::core::models::pixel::pixel",
    "pixelaw::core::models::pixel::Pixel",
    "pixelaw::core::models::pixel::PixelUpdate",
    "pixelaw::core::models::queue::queue_item",
    "pixelaw::core::models::registry::app",
    "pixelaw::core::models::registry::app_name",
    "pixelaw::core::models::registry::app_user",
    "pixelaw::core::models::registry::instruction",
    "pixelaw::core::models::registry::core_actions_address",
    "pixelaw::core::models::permissions::permissions",
    "pixelaw::core::utils::get_core_actions",
    "pixelaw::core::utils::Direction",
    "pixelaw::core::utils::Position",
    "pixelaw::core::utils::DefaultParameters",
    "pixelaw::core::actions::actions",
    "pixelaw::core::actions::IActionsDispatcher",
    "pixelaw::core::actions::IActionsDispatcherTrait",
]
