kind = "DojoModel"
class_hash = "0x18179178f041bcb269bad4eaecc14e07451c457eb6fb4151eb18e7104310d94"
original_class_hash = "0x18179178f041bcb269bad4eaecc14e07451c457eb6fb4151eb18e7104310d94"
abi = "manifests/release/base/abis/models/pixelaw-Block-656ed65c.json"
tag = "pixelaw-Block"
qualified_path = "p_dash::models::block::block"
manifest_name = "pixelaw-Block-656ed65c"

[[members]]
name = "stage_id"
type = "felt252"
key = true

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "blocktype"
type = "BlockType"
key = false
